### ISSUE TITLE
Effort to get this working on Windows

### ISSUE THREAD

**Issue by cfsamson** [outersky/simple_excel_writer#2]
I would like to get this to work on Windows. May I ask if you ever figured out what went wrong when using the zip-crate and/or did you file any issue there that I can look up to see if it has been resolved or not?

**Comment by outersky** [comment]
@cfsamson 
The short answer is sorry,
but there is a workaround to use external zip command .

**Comment by cfsamson** [comment]
@outersky See my PR, I seem to get it to work on my windows machine. I've only ran a handful of tests though but the code runs without errors and the excel files open and displays without problems. 

Sorry in advance for some files getting included in the PR with only formatting changes (ran cargo fmt on the project before I submitted the PR).
