### ISSUE TITLE
Compatibility with Webassembly

### ISSUE THREAD

**Issue by connorskees** [outersky/simple_excel_writer#25]
Hello,

I am hoping to use this library to serialize excel files in the browser. Currently it is not possible to do so because of line 153 here,
<img width="741" alt="Screen Shot 2022-03-04 at 6 09 10 PM" src="https://user-images.githubusercontent.com/39542938/156854226-0a99cadc-38bb-43ee-b6b4-a0bf528725e5.png">

Clicking through we find a call to `time::now`, which is not available to webassembly when executed in the browser
<img width="740" alt="Screen Shot 2022-03-04 at 6 09 44 PM" src="https://user-images.githubusercontent.com/39542938/156854275-d1d479f0-ae8a-4897-bd9c-25926c3668cb.png">

the easiest solutions that i see are to either remove the `"time"` feature from `zip` or to not call `FileOptions::default()`, but rather give an explicit time that does not result in a call to the standard library. 
<img width="639" alt="Screen Shot 2022-03-04 at 7 07 47 PM" src="https://user-images.githubusercontent.com/39542938/156858181-ce85ae0f-a805-4224-a8ce-6a0aadda336b.png">

I am happy to open a pr for either of these solutions if they make sense for this library.

**Comment by outersky** [comment]
Great! Any PR is welcome !
