### ISSUE TITLE
First test running of example

### ISSUE THREAD

**Issue by chn-cutelotus** [outersky/simple_excel_writer#7]
![image](https://user-images.githubusercontent.com/56624787/78618985-9b197180-78ae-11ea-812c-12b30888ddb9.png)
I'm glad to see .xlsx file saved successfully with the above screenshot.
However, it seems that the code "< x m l>< t a g >" doesn't works.

**Comment by outersky** [comment]
Maybe you misunderstand the example :)
Since excel itself uses xml internally, all xml tags must be escaped automatically to prevent danger content .
